#!/bin/bash

# Check out the number of arguments
if [[ "$#" = 0 ]]
then
  MAX_NUMBER_RETRY=3
else
  MAX_NUMBER_RETRY=$1
fi

# Prompt for the input of an integer ranging one and five inclusively
echo -n "Please input a number between one and five in digit and press return when done >"
read INPUT_DIGIT

NUMBER_RETRY=0

while [[ "$INPUT_DIGIT" -lt 1 || "$INPUT_DIGIT" -gt 5 ]]
do
  NUMBER_RETRY=`expr ${NUMBER_RETRY} + 1`
  
  if [[ "$NUMBER_RETRY" -ge "$MAX_NUMBER_RETRY" ]]
  then
    echo "You have failed for three times. We are going to terminate this program."
    exit 1
    break
  else
    echo "Sorry we only accept a number between one and five. Please try again:"
    read INPUT_DIGIT
  fi
done

# Exit the program with a last sentence
echo "The number you entered is ${INPUT_DIGIT}. We are going to terminate this program ${0}." 
exit 0
